# Generated by Django 4.1 on 2022-08-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lesson_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='viewed_lessons',
            field=models.ManyToManyField(blank=True, related_name='users', related_query_name='users', to='core.lesson'),
        ),
    ]
